units:
  ks: 15
  kc: 18.5
  kp: kc + 1
points:
  key:
    height: kc
    width: kc
    spread: kp
    padding: kp
  zones:
    matrix:
      anchor:
        shift: [150, -175]
      columns:
        outer:
          key.splay: 2
          key.column_net: P10
        pinky:
          key.stagger: 2
          key.column_net: P16
        ring:
          key.stagger: 4
          key.splay: -2
          key.spread: kp
          key.column_net: P14
        middle:
          key.stagger: 3
          key.column_net: P15
        index:
          key.splay: -4
          key.stagger: -3
          rows.mod.skip: true
          key.column_net: P18
        inner:
          key.splay: -3
          key.stagger: -5
          key.spread: kc
          rows.mod.skip: true
          key.column_net: P19
      rows:
        mod:
          row_net: P9
        bottom:
          row_net: P8
        home:
          row_net: P7
        top:
          row_net: P6
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [0, -kc - 5]
        rotate: -20
      columns:
        outer:
          key.column_net: P18
        home:
          key.height: 1.5kc
          key.shift: [0, 0.25kc]
          key.column_net: P19
        inner:
          key.height: 1.5kc
          key.shift: [0, 0.25kc]
          key.column_net: P19
      rows:
        cluster:
          row_net: P9
  rotate: 7
outlines:
  switches:
    - what: rectangle
      where: true
      size: [ks, ks]
  keycaps:
    - what: rectangle
      where: true
      size: [kc, kc]
  board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_top
          shift: [-0.5ks, 0.5ks]
        - ref: matrix_outer_top
          shift: [0.5ks, 0.5ks]
        - ref: matrix_pinky_top
          shift: [-0.5ks, 0.5ks]
        - ref: matrix_pinky_top
          shift: [0.5ks, 0.5ks]
        - ref: matrix_ring_top
          shift: [-0.5ks, 0.5ks]
        - ref: matrix_ring_top
          shift: [0.5ks, 0.5ks]
        - ref: matrix_middle_top
          shift: [-0.5ks, 0.5ks]
        - ref: matrix_middle_top
          shift: [0.5ks, 0.5ks]
        - ref: matrix_index_top
          shift: [-0.5ks, 0.5ks]
        - ref: matrix_index_top
          shift: [0.5ks, 0.5ks]
        - ref: matrix_inner_top
          shift: [-0.5ks, 0.5ks]
        - ref: matrix_inner_top
          shift: [2.4ks, 0.5ks]
        - ref: matrix_inner_bottom
          shift: [2.4ks, -0.5ks]
        - ref: thumbfan_inner_cluster
          shift: [0.5ks, 0.75ks]
        - ref: thumbfan_inner_cluster
          shift: [0.5ks, -0.75ks]
        - ref: thumbfan_outer_cluster
          shift: [-0.5ks, -0.5ks]
        - ref: matrix_outer_mod
          shift: [-0.5ks, -0.5ks]
      expand: 5
      joints: round
  combo:
    - name: board
    - operation: subtract
      name: switches
  cap_combo:
    - name: board
    - operation: subtract
      name: keycaps
pcbs:
  left:
    outlines:
      main:
        outline: board
    footprints:
      ks27:
        what: ks27
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [9, 6]
          rotate: -90
      revmicro:
        what: promicro_pretty
        where:
          ref: matrix_inner_top
          shift: [1kc + 3, -6]
          rotate: -90
      niceview:
        what: niceview
        params:
          side: "F"
          reverse: true
          MOSI: P2
          SCK: P3
          CS: P1
        where:
          ref: matrix_inner_top
          shift: [1kc + 3, -8]
      jstph:
        what: jstph
        params:
          pos: BPOS
          neg: GND
        where:
          ref: matrix_inner_home
          shift: [2kc - 3, -8]
          rotate: 180
      jstph_rev:
        what: jstph
        params:
          side: B
          pos: BPOS
          neg: GND
        where:
          ref: matrix_inner_home
          shift: [2kc - 3, -8]
          rotate: 180
      slider:
        what: slider
        params:
          side: F
          from: BPOS
          to: VCC
        where:
          ref: matrix_inner_bottom
          shift: [2kc + 2, 0]
          rotate: -90
      back-slider:
        what: slider
        params:
          side: B
          from: BPOS
          to: VCC
        where:
          ref: matrix_inner_bottom
          shift: [2kc + 2, 0]
          rotate: -90
      reset-left:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref: matrix_inner_bottom
          shift: [1.5kc + 1, 0]
      reset-right:
        what: button
        params:
          from: GND
          to: RST
          side: B
        where:
          ref: matrix_inner_bottom
          shift: [1.5kc + 1, 0]
