units:
  g: 18.5
  pg: g + 4
points:
  zones:
    matrix:
      rows:
        extra:
        bottom:
        home:
        top:
      columns:
        outer:
          key.splay: 2
        pinky:
          key.stagger: 2
        ring:
          key.stagger: 4
          key.splay: -2
          key.spread: 1g + 1
        middle:
          key.stagger: 3
        index:
          key.splay: -3
          key.stagger: -3
          rows.extra.skip: true
        inner:
          key.splay: -2
          key.stagger: -4
          rows.extra.skip: true
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [0, -1.2g]
        rotate: -15
      columns:
        inner:
        middle:
          key.height: 1.5g
          key.shift: [0, 0.25g]
        outer:
          key.height: 1.5g
          key.shift: [0, 0.25g]
      rows:
        thumb:
  rotate: -.75g
  mirror: &mirror
    ref: matrix_inner_top
    distance: 3.5g
outlines:
  raw:
    - what: rectangle
      where: true
      size: [g, g]
  keys:
    - what: rectangle
      where: true
      size: [g-0.5, g-0.5]
  board_left:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_top
          shift: [-0.5pg, 0.5pg]
        - ref: matrix_middle_top
          shift: [-0.5pg, 0.5pg]
        - ref: matrix_middle_top
          shift: [0.5pg, 0.5pg]
        - ref: matrix_inner_top
          shift: [1.8pg, 0.5pg]
        - ref: matrix_inner_bottom
          shift: [1.8pg, -0.5pg]
        - ref: thumbfan_outer_thumb
          shift: [0.5pg, 0.75pg]
        - ref: thumbfan_outer_thumb
          shift: [0.5pg, -0.75pg]
        - ref: thumbfan_inner_thumb
          shift: [-0.5pg, -0.5pg]
        - ref: matrix_outer_extra
          shift: [-0.5pg, -0.5pg]
      fillet: 3
  board_right:
    - what: polygon
      operation: stack
      points:
        - ref: mirror_matrix_outer_top
          shift: [-0.5pg, 0.5pg]
        - ref: mirror_matrix_middle_top
          shift: [-0.5pg, 0.5pg]
        - ref: mirror_matrix_middle_top
          shift: [0.5pg, 0.5pg]
        - ref: mirror_matrix_inner_top
          shift: [1.8pg, 0.5pg]
        - ref: mirror_matrix_inner_bottom
          shift: [1.8pg, -0.5pg]
        - ref: mirror_thumbfan_outer_thumb
          shift: [0.5pg, 0.75pg]
        - ref: mirror_thumbfan_outer_thumb
          shift: [0.5pg, -0.75pg]
        - ref: mirror_thumbfan_inner_thumb
          shift: [-0.5pg, -0.5pg]
        - ref: mirror_matrix_outer_extra
          shift: [-0.5pg, -0.5pg]
      fillet: 3
  combo_left:
    - name: board_left
    - operation: subtract
      name: keys
  combo_right:
    - name: board_right
    - operation: subtract
      name: keys
  full_kb:
    - name: combo_left
    - operation: add
      name: combo_right
